image: node:10

node10:
  stage: test
  image: node:10
  script:
    - node -v
    - npm install standard
    - npm test

node12:
  stage: test
  image: node:12
  script:
    - node -v
    - npm install standard
    - npm test

node14:
  stage: test
  image: node:14
  script:
    - node -v
    - npm install standard
    - npm test

node-latest:
  stage: test
  image: node:latest
  script:
    - node -v
    - npm install standard
    - npm test
